<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="8" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-20T12:49:27 IST" name="Data Driven Basics" finished-at="2021-12-20T12:49:28 IST" duration-ms="597">
    <groups>
    </groups>
    <test started-at="2021-12-20T12:49:27 IST" name="Unit Test Cases" finished-at="2021-12-20T12:49:28 IST" duration-ms="597">
      <class name="com.w2a.testcases.AllUnitTestCases">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.w2a.testcases.AllUnitTestCases@4bf3798b]" started-at="2021-12-20T12:49:21 IST" name="setUp" finished-at="2021-12-20T12:49:27 IST" duration-ms="5700" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="createUnitWithBlankData()[pri:0, instance:com.w2a.testcases.AllUnitTestCases@4bf3798b]" started-at="2021-12-20T12:49:27 IST" name="createUnitWithBlankData" finished-at="2021-12-20T12:49:28 IST" duration-ms="419" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test case forcefully failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test case forcefully failed
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testcases.AllUnitTestCases.createUnitWithBlankData(AllUnitTestCases.java:386)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUnitWithBlankData -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.w2a.testcases.AllUnitTestCases@4bf3798b]" started-at="2021-12-20T12:49:28 IST" name="tearDown" finished-at="2021-12-20T12:49:30 IST" duration-ms="1601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AllUnitTestCases -->
    </test> <!-- Unit Test Cases -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
